name: Build Android APK Only

on:
  push:
    branches: [ master, main ]
  workflow_dispatch: # Manual trigger also available

jobs:
  build-android:
    runs-on: ubuntu-latest
    name: Build Android APK
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Show environment info
      run: |
        echo "=== Environment Information ==="
        echo "Java version:"
        java -version
        echo "Android SDK location: $ANDROID_HOME"
        echo "Android SDK contents:"
        ls -la $ANDROID_HOME/ || echo "ANDROID_HOME not set"
        echo ".NET version:"
        dotnet --version
        
    - name: Install .NET MAUI Android Workload
      run: |
        echo "=== Installing MAUI Android Workload ==="
        dotnet workload install maui-android
        echo "=== Installed Workloads ==="
        dotnet workload list
        
    - name: Restore dependencies
      run: |
        echo "=== Restoring Dependencies ==="
        dotnet restore --verbosity normal
        
    - name: Build Android APK
      run: |
        echo "=== Building Android APK ==="
        dotnet build -f net8.0-android -c Release --verbosity normal
        
    - name: Find APK files
      run: |
        echo "=== Searching for APK files ==="
        echo "Current directory:"
        pwd
        echo ""
        echo "Looking for APK files in common locations:"
        find . -name "*.apk" -type f 2>/dev/null || echo "No APK files found"
        echo ""
        echo "Build output directory structure:"
        find ./bin -type d 2>/dev/null || echo "No bin directory found"
        echo ""
        echo "Contents of bin/Release/net8.0-android/:"
        ls -la ./bin/Release/net8.0-android/ 2>/dev/null || echo "Directory not found"
        echo ""
        echo "Looking for APK in android-x64 subdirectories:"
        find ./bin/Release/net8.0-android -name "*.apk" -type f 2>/dev/null || echo "No APK files found in android-x64"
        
    - name: Upload Android APK
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: android-apk
        path: |
          bin/Release/net8.0-android/android-x64/Release/*.apk
          bin/Release/net8.0-android/android-x64/Debug/*.apk
          bin/Release/net8.0-android/*.apk
          bin/Release/net8.0-android/**/*.apk
