name: Build Android APK Only

on:
  push:
    branches: [ master, main ]
  workflow_dispatch: # Manual trigger also available

jobs:
  build-android:
    runs-on: ubuntu-latest
    name: Build Android APK
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Show environment info
      run: |
        echo "=== Environment Information ==="
        echo "Java version:"
        java -version
        echo "Android SDK location: $ANDROID_HOME"
        echo "Android SDK contents:"
        ls -la $ANDROID_HOME/ || echo "ANDROID_HOME not set"
        echo ".NET version:"
        dotnet --version
        
    - name: Install .NET MAUI Android Workload
      run: |
        echo "=== Installing MAUI Android Workload ==="
        dotnet workload install maui-android
        echo "=== Installed Workloads ==="
        dotnet workload list
        
    - name: Restore dependencies
      run: |
        echo "=== Restoring Dependencies ==="
        dotnet restore --verbosity normal
        
    - name: Build Android APK
      run: |
        echo "=== Building Android APK ==="
        dotnet build -f net8.0-android -c Release --verbosity normal
        
    - name: Check build output
      run: |
        echo "=== Checking Build Output ==="
        echo "Looking for APK files:"
        find . -name "*.apk" -o -name "*.aab" || echo "No APK/AAB files found"
        echo "Build output directory:"
        ls -la bin/Release/net8.0-android/ || echo "Build output directory not found"
        
    - name: Upload Android APK
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: android-apk
        path: bin/Release/net8.0-android/android-x64/Release/*.apk
