name: Build Android APK Only

on:
  workflow_dispatch: # Manual trigger only

jobs:
  build-android:
    runs-on: ubuntu-latest
    name: Build Android APK
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install .NET MAUI workload
      run: dotnet workload install maui
      
    - name: Build Android APK
      run: dotnet build -f net8.0-android -c Release
      
    - name: Upload Android APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: bin/Release/net8.0-android/android-x64/Release/*.apk
