name: Build Mobile App (Simple) - DISABLED

# This workflow is disabled to avoid automatic builds
# Use android-only.yml instead for manual Android builds

# on:
#   push:
#     branches: [ main, master ]
#   pull_request:
#     branches: [ main, master ]
#   workflow_dispatch: # Allow manual trigger

# jobs:
#   build-android:
#     runs-on: ubuntu-latest
#     name: Build Android APK
