name: Build Android APK Only

on:
  workflow_dispatch: # Manual trigger only

jobs:
  build-android:
    runs-on: ubuntu-latest
    name: Build Android APK
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Show environment info
      run: |
        echo "Java version:"
        java -version
        echo "Android SDK location:"
        echo $ANDROID_HOME
        echo "Android SDK tools:"
        ls -la $ANDROID_HOME/tools/bin/ || echo "Tools not found"
        echo "Android SDK platforms:"
        ls -la $ANDROID_HOME/platforms/ || echo "Platforms not found"
      
    - name: Install .NET MAUI Android Workload
      run: |
        dotnet workload install maui-android
        dotnet workload list
        dotnet --info
      
    - name: Restore dependencies
      run: dotnet restore --verbosity normal
      
    - name: Build Android APK
      run: |
        dotnet build -f net8.0-android -c Release --verbosity normal
        echo "Build completed. Checking output directory:"
        ls -la bin/Release/net8.0-android/ || echo "Output directory not found"
      
    - name: Upload Android APK
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: android-apk
        path: bin/Release/net8.0-android/android-x64/Release/*.apk
